# Generated by Django 6.0.5 on 2026-05-13 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_email_campaigncontact_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='secure',
            new_name='use_ssl',
        ),
        migrations.AddField(
            model_name='identity',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='smtp_from_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='smtp_pass',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='identity',
            name='smtp_user',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('user', 'name')},
        ),
    ]
