# Generated by Django 5.2.14 on 2026-05-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_rename_secure_identity_use_ssl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='delay_ms',
            field=models.IntegerField(default=45000),
        ),
        migrations.CreateModel(
            name='TrackedOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'tracked_opens',
                'indexes': [models.Index(fields=['campaign', 'recipient'], name='tracked_ope_campaig_48c9b1_idx')],
            },
        ),
    ]
