# Generated by Django 5.2.14 on 2026-06-28 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_delay_ms_trackedopen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='daily_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='daily_limit',
            field=models.IntegerField(default=295),
        ),
        migrations.AddField(
            model_name='identity',
            name='daily_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IdentityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identities', models.ManyToManyField(to='campaigns.identity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_groups',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='identity_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.identitygroup'),
        ),
    ]
