# Generated by Django 5.2.14 on 2026-06-28 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_identity_daily_date_identity_daily_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('csv_content', models.TextField()),
                ('columns', models.JSONField(default=list)),
                ('row_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_csvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_csvs',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
