# Generated by Django 5.2.14 on 2026-07-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_savedcsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='smtp_from_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
